---
title: "Academic and Professional Experience"
---

Thanks for taking a look at my page! Here's what I've been up to. If you're interested, you can take a peek at my full resume [here](data/Tatini Mal-Sarkar cv_july 2018 copy.pdf).

### Academic Experience

* Columbia University, **Mailman School of Public Health**

    *Epidemiology*, New York, NY, 2017-2019
  
* Columbia University, **Columbia College**

    *Sociology, Psychology*, New York, NY, 2013-2017
  
* **Hathaway Brown School**

    Shaker Heights, OH, 2007-2013



### Professional Experience

* Columbia University, **Mailman School of Public Health**

    Teaching Assistant (Quantitative Research Methods)

    Research Assistant (Psychiatric Epidemiology)

    Vice President of External Affairs (Emerging Women's Leadership)


* **American Institute for Cognitive Therapy**

    Clinical Research Assistant

* Columbia University, **Columbia College**

    Rabi Scholar
    
    Research Assistant (Social Psychology, Biology)

    Features Editor, Daily Editor (Bwog)

    Radio Show Host (WBAR)
